stages:
  - test
  - deploy

# run SAST (Security tests)
include:
- template: Security/SAST.gitlab-ci.yml

pages:
  image: node:14
  stage: deploy
  script:
    - set -e
    - npm install
    - npm run generate
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

purge_cache:
  image: curlimages/curl:7.78.0
  stage: .post
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - |
      set -e
      curl -X "POST" "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
           -H "X-Auth-Email: ${CF_EMAIL}" \
           -H "Authorization: Bearer ${CF_PURGE_KEY}" \
           -H 'Content-Type: application/json' \
           -d $'{
        "purge_everything": true
      }'



