stages:
  - test
  - build
  - deploy

build:
  image: node:14
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  script:
    - set -e
    - npm ci --cache .npm --prefer-offline
    - npm run generate
    - cp -r dist public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "staging"'

.deploy:
  stage: deploy
  image: eeacms/rsync:2.3
  artifacts:
    paths:
      - public
  script:
    - chmod 400 $SSH_KEY
    - rsync -Pavp --mkpath --delete --rsh="ssh -p ${SSH_PORT} -i ${SSH_KEY} -o StrictHostKeyChecking=no" ${CI_PROJECT_DIR}/public/* ${SSH_USER}@${SSH_IP}:/home/adopotvj/${DEPLOY_PATH}

deploy_main:
  extends:
    - .deploy
  variables:
    DEPLOY_PATH: "public_html/2022"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: live
    url: https://adoptingbitcoin.org/2022

deploy_staging:
  extends:
    - .deploy
  variables:
    DEPLOY_PATH: "staging.adoptingbitcoin.org/2022"
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
  environment:
    name: staging
    url: https://staging.adoptingbitcoin.org/2022

deploy_mr:
  extends:
    - .deploy
  variables:
    DEPLOY_PATH: "staging.adoptingbitcoin.org/2022-MR/${CI_COMMIT_REF_NAME}"
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'staging'
      when: never
  environment:
    name: mr/$CI_COMMIT_REF_NAME
    url: https://$DEPLOY_PATH


purge_cache:
  image: curlimages/curl:7.78.0
  stage: .post
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "staging"'
  script:
    - |
      set -e
      curl -X "POST" "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
           -H "X-Auth-Email: ${CF_EMAIL}" \
           -H "Authorization: Bearer ${CF_PURGE_KEY}" \
           -H 'Content-Type: application/json' \
           -d $'{
        "purge_everything": true
      }'
